REPORT 汪子熙的Report，吓死人了!!!!!.

INCLUDE NOT.

IF  NOT NOT NOT  NOT NOT NOT  NOT NOT NOT NOT NOT NOT
NOT NOT NOT NOT  NOT NOT NOT  NOT NOT NOT !NOT OR NOT
NOT NOT !NOT OR  NOT NOT NOT NOT NOT=>NOT( NOT ) AND
NOT NOT NOT !NOT OR NOT NOT !NOT  AND NOT !NOT  ... NOT.